version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    # ./frontend is local folder, which is mapped to the container project folder /app
    # Changes in local ./frontend will override content of container's /app folder
    volumes:
      - /app/node_module
      - ./frontend:/app
  api:
    build: ./api
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
# custom mongo db volume inside Docker
volumes:
  mongodb_data: